// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApBOAejQ2GXhz4ogEMWzE_RSLHDvOcYJo',
    appId: '1:382449873301:web:e57be43c45792ef794069c',
    messagingSenderId: '382449873301',
    projectId: 'lory-app-fb818',
    authDomain: 'lory-app-fb818.firebaseapp.com',
    storageBucket: 'lory-app-fb818.firebasestorage.app',
    measurementId: 'G-TX9MFWWZ02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJGy0hq3HxrHaASew-3wbaC2NRTJMymyc',
    appId: '1:382449873301:android:e6550d205e9f46d794069c',
    messagingSenderId: '382449873301',
    projectId: 'lory-app-fb818',
    storageBucket: 'lory-app-fb818.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfuNC1nqHjNuqBMPnjTRLEAoNyX6Y6j58',
    appId: '1:382449873301:ios:23935f680611163294069c',
    messagingSenderId: '382449873301',
    projectId: 'lory-app-fb818',
    storageBucket: 'lory-app-fb818.firebasestorage.app',
    iosClientId: '382449873301-ghgo51977uvjt2qtlbp229akj6u56b23.apps.googleusercontent.com',
    iosBundleId: 'com.example.lory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfuNC1nqHjNuqBMPnjTRLEAoNyX6Y6j58',
    appId: '1:382449873301:ios:692014ab4e27199994069c',
    messagingSenderId: '382449873301',
    projectId: 'lory-app-fb818',
    storageBucket: 'lory-app-fb818.firebasestorage.app',
    iosClientId: '382449873301-45rb6usurstbjq9m8nfuggk07ofcntl5.apps.googleusercontent.com',
    iosBundleId: 'com.example.hutechCampus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApBOAejQ2GXhz4ogEMWzE_RSLHDvOcYJo',
    appId: '1:382449873301:web:d8a2bf870b09259994069c',
    messagingSenderId: '382449873301',
    projectId: 'lory-app-fb818',
    authDomain: 'lory-app-fb818.firebaseapp.com',
    storageBucket: 'lory-app-fb818.firebasestorage.app',
    measurementId: 'G-6KVJVXF66G',
  );
}
